[project]
name = "function-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=6.29.5",
    "openai>=1.86.0",
    "requests>=2.32.4",
    "rich>=14.0.0",
]
